version: 0.2
 
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - make ecr-login
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - make test
      - make build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - make ecr-push
      - {"Version":"latest","ImageURI":"631938344310.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-sample:latest"}
      - printf '{"Version":"latest","ImageURI":"%s"}' 631938344310.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-sample:latest > imagedefinitions.json

artifacts:
  ## buildの最後で作成したファイルをアーティファクトとして流す
  type: zip
  files: imagedefinitions.json
